AWSTemplateFormatVersion: "2010-09-09"
Description: "gocontainer"
Parameters:
  IP8080:
    Type: String
  IP22:
    Type: String    
Resources:
  gocontainersecgrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: gocontainersecgrp
  Server:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: gocontainer
      ImageId: ami-bf4193c7
      InstanceType: m4.large
      KeyName:  oregonkeypair
      SecurityGroupIds: 
        - !Ref gocontainersecgrp
      IamInstanceProfile: RoleForTestingRoles
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            -
              - "#!/bin/bash -ex\n"      
              - "yum install git -y\n"
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user; git clone -b go https://github.com/craigwongva/gocontainer.git > /tmp/u01 2>&1 '\n"
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user/gocontainer; ./userdata/install "
              - !Ref IP8080
              - " "
              - !Ref IP22
              - " > /tmp/u02 2>&1'\n"
Outputs:
  InstanceID:
    Description: "The Instance ID"
    Value: !GetAtt Server.PublicIp
