M centos
MAINTAINER cwong@radiantblue.com
RUN yum install git -y
RUN yum install wget -y
RUN wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
RUN tar -xzf go1.4.2.linux-amd64.tar.gz -C /usr/local
RUN rm go1.4.2.linux-amd64.tar.gz
RUN git clone https://github.com/venicegeo/pzsvc-hello.git
RUN mkdir -p /src/pzhello
RUN cp pzsvc-hello/main.go src/pzhello
ENV GOROOT=/usr/local/go
ENV GOPATH=/
ENV PATH=$PATH:$GOROOT/bin
RUN go get github.com/venicegeo/pz-gocommon
RUN go get github.com/gin-gonic/gin
RUN go install pzhello
CMD ["/bin/pzhello"]

