FROM centos
MAINTAINER cwong@radiantblue.com

#Test this script:
# vi Dockerfile
# docker build -t mycontainer:0.1 .
# docker run -p 8080:8080 <sha of image produced by the docker build>




#I'm not sure why/how, but the Nexus repo by default is publicly viewable.
#This seems to cause an error if the file doesn't exist: RUN rm /first_webapp_from_nexus
RUN yum install wget -y
RUN wget http://52.41.214.100:8081/repository/myrawrepo/first_webapp_from_nexus
RUN chmod +x first_webapp_from_nexus
CMD ["/first_webapp_from_nexus"]

