AWSTemplateFormatVersion: "2010-09-09"
Description: "gocontainer"
Resources:
  gocontainersecgrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: gocontainersecgrp
#      SecurityGroupIngress:
#      - CidrIp: 22.22.22.22/32
#        FromPort: 22
#        IpProtocol: tcp
#        ToPort: 22
  Server:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: craigLF
      ImageId: ami-bf4193c7
      InstanceType: m4.xlarge
      KeyName:  oregonkeypair
      SecurityGroupIds: 
        - !Ref gocontainersecgrp
      IamInstanceProfile: RoleForTestingRoles
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 16
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            -
              - "#!/bin/bash -ex\n"      
              - "yum install git -y\n"
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user; git clone -b go https://github.com/craigwongva/gocontainer.git > /tmp/u01 2>&1 '\n"
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user/gocontainer; ./userdata'\n"
Outputs:
  InstanceID:
    Description: "The Instance ID"
    Value: !GetAtt Server.PublicIp
