FROM centos
MAINTAINER cwong@radiantblue.com

RUN yum install wget -y
RUN wget https://storage.googleapis.com/golang/go1.5.linux-amd64.tar.gz
RUN tar -xzf go1.5.linux-amd64.tar.gz -C /usr/local
ENV GOROOT /usr/local/go
ENV GOPATH /
ENV PATH $PATH:$GOROOT/bin
RUN cd /
RUN yum install git -y
RUN git clone https://github.com/venicegeo/pz-uuidgen
RUN mkdir /src
RUN mkdir /src/pz-uuidgen
RUN cp /pz-uuidgen/main.go /src/pz-uuidgen
RUN go get github.com/venicegeo/pz-gocommon/gocommon
RUN go get github.com/venicegeo/pz-uuidgen/uuidgen
RUN go install pz-uuidgen

CMD ["/bin/sh", "-c", "/bin/pz-uuidgen > /tmp/pz-uuidgen-port-number-line 2>&1"]
