FROM centos
MAINTAINER cwong@radiantblue.com

RUN yum install wget -y
RUN wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
RUN tar -xzf go1.4.2.linux-amd64.tar.gz -C /usr/local
ENV GOROOT /usr/local/go
ENV GOPATH /
ENV PATH $PATH:$GOROOT/bin
RUN cd /
RUN yum install git -y
RUN git clone https://github.com/venicegeo/pz-logger
RUN mkdir /src
RUN mkdir /src/pz-logger
RUN cp /pz-logger/main.go /src/pz-logger
RUN go get github.com/venicegeo/pz-gocommon/gocommon
RUN go get github.com/venicegeo/pz-logger/logger
RUN go install pz-logger

#doesn't work: CMD "/bin/pz-logger > /tmp/pz-logger-port-number-line 2>&1"
CMD ["/bin/sh", "-c", "/bin/pz-logger > /tmp/pz-logger-port-number-line 2>&1"]
