FROM centos
MAINTAINER cwong@radiantblue.com

#Test this script:
# vi Dockerfile
# docker build -t mycontainer:0.1 .
# docker run -p 8080:8080 <sha of image produced by the docker build>




#I'm not sure why/how, but the Nexus repo by default is publicly viewable.
#This seems to cause an error if the file doesn't exist: RUN rm /first_webapp_from_nexus
ARG WHEREISNEXUS
RUN yum install wget -y
RUN wget http://$WHEREISNEXUS:8079/repository/myrawrepo/piazza-ingest-0.1.0-NEXUSSED.jar
RUN yum install java-1.8.0-openjdk-devel -y
ENV vcap.services.pz-blobstore.credentials.access_key_id AKIA
ENV vcap.services.pz-blobstore.credentials.secret_access_key BPkA

CMD ["/usr/lib/jvm/java-1.8.0-openjdk/bin/java", "-Dlogger.protocol=http", "-Dlogger.port=37435", "-jar", "piazza-ingest-0.1.0-NEXUSSED.jar"]
