node { 
    def mvn = tool 'M3.0.5' 
    def TEST_STACK_NAME = 'craigu01'
    def TEST_STACK_IP

    stage('buildTestInstanceWithApp') {
      println "---buildTestInstanceWithApp---"
      def s = ''
      s += 'aws cloudformation create-stack '
      s += "--stack-name ${TEST_STACK_NAME} " 
      s += '--template-url '
      s += 'https://s3.amazonaws.com/'
      s += 'venicegeo-devops-dev-gocontainer-project/'
      s += 'cf-nexus-java.json ' 
      s += '--region us-west-2 ' 
      s += '--parameters ' 
      s += 'ParameterKey=nexususername,ParameterValue=unused '
      s += 'ParameterKey=nexuspassword,ParameterValue=unused'
      s += 'ParameterKey=tomcatmgrpassword,ParameterValue=unused '
      sh s
    }

    stage('sleep60') {
      sh 'sleep 60'
    }

    stage('describeTestInstance') {
      println "---describeTestInstance---"
      def s = ''
      s += 'aws cloudformation describe-stacks '
      s += "--stack-name ${TEST_STACK_NAME} "
      s += '--region us-west-2'
      def x = sh(script: s, returnStdout: true)
      def temp = (x =~ /"OutputValue": "(.*)"/)
      TEST_STACK_IP = temp[0][1]
      println "TEST_STACK_IP is $TEST_STACK_IP"
      //Jenkins question: The following statement seems
      // to cause a Jenkins failure.
      //sh "sleep 1500"
    }

    stage('sleep1500') {
      sh 'sleep 1500'
    }

    stage('invokePhantomOnApp') {
      println "---waitThenInvokePhantomOnApp---"
      sh "BUILD_ID=dontKillMe ./invoke-phantom ${TEST_STACK_IP} &"
    }

    stage('sleep61') {
      println "---sleep61---"
      sh "sleep 60"
    }

    stage('curlAndInterpretAppStatus') {
      println "---curlAndInterpretAppStatus---"

      //Groovy question: Why is this a day plus?
      // sleep(1000*60*2) 

      def mickey = [
        "curl",  
        "${TEST_STACK_IP}:8080/green/timer/status"]
         .execute().text
      def ARBITRARY_SUCCESS_PCT = 0.95
      def NUM_GREEN_DOTS = 100
      def GREEN_DOT_STATUS_DONE = '4'

      //Groovy notes:
      //fails: 
      // if (mickey.indexOf(
      //   GREEN_DOT_STATUS_DONE.multiply(
      //     ARBITRARY_SUCCESS_PCT*NUM_GREEN_DOTS)) < 0) { }
      //succeeds: 
      // if (mickey.indexOf('4'.multiply(95)) < 0) { }

      if (mickey.indexOf(
        '4444444444444444444444444444444444444444444444444444444444') < 0) {
    	error "red rover3 ${TEST_STACK_IP}:8080/green/timer/status $mickey" 
      }
    }

    stage('checkoutGreen') {
      println "---checkout---"
      //gvs-2017-ss is an arbitrary name
      dir('gvs-2017-ss') {
        git branch: 'master', url: 'https://github.com/craigwongva/green.git'
      }

      checkout([
        $class: 'GitSCM', 
        branches: [[name: '*/master']], 
        doGenerateSubmoduleConfigurations: false, 
        extensions: [], 
        submoduleCfg: [], 
        userRemoteConfigs: [[url: 'https://github.com/craigwongva/green']]
      ]) 
    } 

    stage('rebuildApp') { 
      println "---rebuildApp---"
      dir('gvs-2017-ss') {
        git branch: 'master', url: 'https://github.com/craigwongva/green.git'
      }
      sh "/usr/local/apache-maven/bin/mvn clean -DskipTests install"
    } 

    stage('deployAppToTestInstanceTomcat') { 
      println "---deployAppToTestInstanceTomcat---"
      def s = '' +
        'scp -i /home/jenkins/craigradiantblueoregon.pem '
        '-o StrictHostKeyChecking=no '
        '/var/lib/jenkins/.m2/repository/com/demo/'
        'green/1.0-SNAPSHOT/green-1.0-SNAPSHOT.war '
        "ec2-user@${TEST_STACK_IP}:/usr/share/tomcat7/webapps/green.war"
      sh s
    }

    stage('cleanup') { 
      println "---cleanup---"
      sh "pkill -f phantomjs || true"
      //sh "aws cloudformation delete-stack --stack-name ${TEST_STACK_NAME}  --region us-west-2"
    }
}
